# Generated by Django 2.2.3 on 2021-12-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_roder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='roder_id',
            new_name='order_id',
        ),
    ]
